variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:linux:
  image: trilogic/linux:9.2
  stage: build
  tags:
        - linux
  script:
        - conan create . trilogic/stable
        - conan user -p trilogic trilogic -r trilogic
        - conan upload "dektec-dtapi/1807.0@trilogic/stable" --all -r trilogic

build:windows:
  stage: build
  tags:
        - windows
  script:
        - conan create . trilogic/stable
        - conan user -p trilogic trilogic -r trilogic
        - conan upload "dektec-dtapi/1807.0@trilogic/stable" --all -r trilogic
